 # ============================================================================
 #  This file is part of ASLI (A Simple Lattice Infiller)
 #  Copyright (C) KU Leuven, 2019-2024
 #
 #  ASLI is free software: you can redistribute it and/or modify it under the 
 #  terms of the GNU Affero General Public License as published by the Free 
 #  Software Foundation, either version 3 of the License, or (at your option) 
 #  any later version.
 #
 #  ASLI is distributed in the hope that it will be useful, but WITHOUT ANY 
 #  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
 #  FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for 
 #  more details.
 #
 #  You should have received a copy of the GNU Affero General Public License
 #  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #  Please read the terms carefully and use this copy of ASLI only if you
 #  accept them.
 # ============================================================================

# ----  CONFIGURATION FILE  ---- #

# Input & output files
files:
  stl: inputs/cube.stl # Object to be provided of an infill in .stl format.
  tap: inputs/cube.tap # Variable unit cell type data in .tap format. [optional]
  sap: inputs/cube.sap # Variable unit cell size data in .sap format. [optional]
  fap: inputs/cube.fap # Variable unit cell feature data in .fap format. [optional]
  output: outputs/cube.* # Output location. [optional, default=outputs/]

# Lattice settings
lt_type: gyroid # Unit cell type: gyroid, sheet_gyroid, diamond, sheet_diamond, primitive, sheet_primitive, IWP, sheet_IWP or cubic. To assign multiple unit cell types set to hybrid and provide a .tap file.
#lt_type_side: scaffold # Side of the lattice to discretize: scaffold (default), void or all. [optional]
#lt_type_filterRadius: 1.0 # Radius specifying the size of hybrid regions. Scales with local unit cell size. [hybrid mode option]
#lt_type_correctionFactor: 0.25 # Correction factor to compensate for the thinning effect of hybridization. [hybrid mode option]

lt_size: 1 # Unit cell size. To assign a variable size set to 0 and provide a .sap file. 

lt_feature: volumeFraction # Unit cell feature: volumeFraction, isovalue, wallSize or poreSize.
lt_feature_val: 0.5 # Unit cell feature value. To assign variable feature values set to 0 and provide a .fap file. (Isovalues provided must be normalized)
#lt_feature_mode: relative # Feature size mode: relative (default) or absolute. In relative mode, wall and pore sizes provided are relative to a 1x1x1 unit cell. [optional]

# User defined feature settings (To use set lt_feature to userDefined) [Unsupported]
#udf_userDefinedFeature: elasticModulus # User defined feature label. [optional]
#udf_A: 110000 # User defined constant 1. [optional]
#udf_B: 1 # User defined constant 2. [optional]
#udf_C: 2 # User defined constant 3. [optional]
#udf_D: 0 # User defined constant 4. [optional]
#udf_E: 0 # User defined constant 5. [optional]

# Mesh settings
me_mesher: CGAL # Mesh library: CGAL or MMG.
me_nThreads: 1 # Number of threads. [optional, default=1, parallel mode only available with CGAL]
me_elementSize: 0.5 # Size of mesh elements. In CGAL an upper bound on the circumradii of the mesh tetrahedra and radii of surface Delaunay balls, in MMG the edge size. Scales with the local wall or pore size depending on the side discretized.
#me_volumeMesh: FALSE # Set to TRUE to obtain both, a volume mesh and a surface triangulation. Set to FALSE to obtain only a surface triangulation. [optional, default=FALSE]

# Mesh settings (CGAL)
CGAL_facetDistance: 0.01 # Surface approximation error as an upper bound for the distance between the circumcenter of a surface facet and the center of a surface Delaunay ball of this facet. Scales with the local unit cell size . [optional, default=0.01]
#CGAL_relativeErrorBound: 1e-3 # Relative error bound used to compute intersection points between the implicit surface and query segments. The bisection is stopped when the length of the intersected segment is less than the product of relative_error_bound by the diagonal of the mean unit cell size [optional, default=1e-3]
#CGAL_facetAngle: 30 # Facet shape quality measure as a lower bound for the surface facets angle in degrees. [optional, default=30]
#CGAL_cellRadiusEdgeRatio: 3.0 # Tetrahedron shape quality measure as an upper bound for the ratio between the circumradius of the tetrahedron and its shortest edge. [optional, default=3.0, only active if volumeMesh=TRUE]

# Mesh settings (MMG)
MMG_hausd: 0.3 # Surface approximation error as a maximal Hausdorff distance. Scales with the mean unit cell [optional, default=0.3]
#MMG_hgrad: 1.3 # Gradation value. [optional, default=1.3, only active if volumeMesh=TRUE]
#MMG_hinitial: 0.36 # Base mesh size. Scales with the local smallest feature size. [optional, default=0.36]

# Note: Parameters used at their default values and optional parameters not used can be removed from the configuration file if desired.