 # ============================================================================
 #  This file is part of ASLI (A Simple Lattice Infiller)
 #  Copyright (C) KU Leuven, 2019-2023
 #
 #  ASLI is free software: you can redistribute it and/or modify it under the 
 #  terms of the GNU Affero General Public License as published by the Free 
 #  Software Foundation, either version 3 of the License, or (at your option) 
 #  any later version.
 #
 #  ASLI is distributed in the hope that it will be useful, but WITHOUT ANY 
 #  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
 #  FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for 
 #  more details.
 #
 #  You should have received a copy of the GNU Affero General Public License
 #  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #  Please read the terms carefully and use this copy of ASLI only if you
 #  accept them.
 # ============================================================================

# ----  CONFIGURATION FILE  ---- #

# Input & output files
files:
  stl: inputs/cube.stl # Object to be provided of an infill as an Stl file.
  tap: inputs/cube.tap # Type at point file. [Use to assign multiple unit cell types] (optional)
  sap: inputs/cube.sap # Size at point file. [Use to assign a non-constant unit cell size] (optional)
  fap: inputs/cube.fap # Feature at point file. [Use to assign a non-constant unit cell feature value] (optional)
  output: outputs/ # Location of the output files. By default the output files are stored in the "outputs" folder.

# Lattice settings
lt_type: gyroid # Unit cell type: gyroid, sheet_gyroid, diamond, sheet_diamond, primitive, sheet_primitive, IWP or sheet_IWP. If multiple unit cell types are desired set to hybrid and provide a .tap file.
lt_type_filterRadius: 1.0 # Radius specifying the size of hybrid regions. Scales with local unit cell size. (Hybrid mode option)
lt_type_correctionFactor: 0.25 # Correction factor to compensate for the thinning effect of hybridization. (Hybrid mode option)

lt_size: 0.5 # Unit cell size. Set to a value > 0 for a constant unit cell size. If a variable size is desired set to 0 and provide a .sap file. 

lt_feature: isovalue # Unit cell feature: isovalue, volumeFraction, wallSize or poreSize.
lt_feature_val: 0.5 # Unit cell feature value. Set to a value > 0 for a constant feature value. If a variable feature value is desired set to 0 and provide a .fap file. [If the feature provided is the isovalue it should be specified as a normalized isovalue!]
lt_feature_mode: relative # Feature size mode: absolute or relative. (Only applies to wall and pore size, default feature_mode is relative) [If set to relative, provide wall and pore sizes for a 1x1x1 unit cell]

# Material properties (Unsupported feature) [Tag: elasticModulus]
mp_materialModel: gibson_ashby # Material model: gibson_ashby [1]. GyroidYan2015 [Yan2015|Gibson-Ashby model] 
mp_solid: 110000 # Elastic modulus of solid material
mp_C: 1 # Gibson, Ashby et al. constant
mp_n: 2 # Gibson, Ashby et al. constant
#mp_C1: 0 # Gibson, Ashby et al. constant
#mp_n1: 0 # Gibson, Ashby et al. constant

# Mesh settings
me_mesher: CGAL # Mesh library: CGAL or MMG.
me_side: scaffold # Side of scaffold to discretize: scaffold or void.
me_volumeMesh: FALSE # Set to TRUE to also get a volume mesh, otherwise set to FALSE.
me_nThreads: 1 # Number of threads (parallel mode is currently only available with CGAL)

# Mesh settings (CGAL)
me_facetAngle: 0 # Surface facet shape (optional, default facet angle is 30 degrees) [Lower bound for the surface facets angle in degrees]
me_facetSize: 0 # Surface facet size. Scales with unit cell size. (optional, defaults to the local unit cell size) [Upper bound for the radii of surface Delaunay balls]
me_facetDistance: 0.015 # Surface approximation error. Scales with the unit cell size [Upper bound for the distance between the circumcenter of a surface facet and the center of a surface Delaunay ball of this facet]
me_cellRadiusEdgeRatio: 0 # Tetrahedron shape quality measure. Value must be larger than 2. (optional, default edge ratio is 3.0. Only used when preserve edges is set to FALSE) [Upper bound for the ratio between the circumradius of a mesh tetrahedron and its shortest edge]
me_cellSize: 0 # Tetrahedra size. Scales with wall size and overrides me_facetSize if me_volumeMesh if set to TRUE. (optional, defaults to the local wall size . Only used when preserve edges is set to FALSE) [Upper bound on the circumradii of the mesh tetrahedra]
me_poissonOffset: 0 # Poisson reconstruction offset. Scales with largest unit cell size in the design. Set to value >= 0.1 (optional, default offset is 0.5)

# Mesh settings (MMG)
me_hvol: 0 # Tetgen max. volume constraint. Scales with the the smallest unit cell size in the design. (optional)
me_hinitial: 0 # Base mesh size. Scales with the smallest feature size. (optional, default hinitial is 0.36)
me_hmin: 0 # Min. edge size. Scales with the smallest feature size in the design. (optional)
me_hmax: 0 # Max. edge size. Scales with the largest feature size in the design. (optional)
me_hausd: 0.42 # Maximal Hausdorff distance for the boundaries approximation. Scales with the mean feature size.
me_hgrad: 0 # Gradation value. (optional, default gradation value is 1.3. Only used when volume mesh is set to TRUE)

# Note: Set optional parameters to 0 to use in default mode.